### PR TITLE
ADDED contributing.md File

### LINKED ISSUE #6: Create a contributing.md file
The file must contain all the guidelines required for the contributors while contributing to the project.

### PR DESCRIPTION
**Pull request by vasav-prashar**
Please review for any changes and merge

### CODE REVIEW

**Comment by itisaby** [comment]
It looks good, but I can't merge it in main, because you were not assigned for this also u didn't ask for it. 
@vasav-prashar

**Comment by vasav-prashar** [comment]
sir i thought it was open for pr

**Comment by vasav-prashar** [comment]
please assign and merge for me🙂

**Review by itisdb — COMMENTED** [review]
please check the tag with alt: check. this one is not loading.

**Comment by vasav-prashar** [comment]
image
check here working for me

**Pull request merged**
