### PR TITLE
added contributing.md

### LINKED ISSUE #6: Create a contributing.md file
The file must contain all the guidelines required for the contributors while contributing to the project.

### PR DESCRIPTION
**Pull request by MohammedHamzaMalik**
Created and added a contributing.md file.
Issue [#6](https://github.com/acm-iem/Twitter-Bot/issues/6)

Kindly review it and merge it @itisaby.

### CODE REVIEW

**Comment by itisaby** [comment]
Yup looks good to me but can you please add some more guidelines before creating a PR like you have to ask the admin just like you did and linking the issue while doing the PR so that everyone follows it make the process smooth

**Comment by MohammedHamzaMalik** [comment]
> Yup looks good to me but can you please add some more guidelines before creating a PR like you have to ask the admin just like you did and linking the issue while doing the PR so that everyone follows it make the process smooth

Yeah, sure I will.

**Review by itisaby — CHANGES_REQUESTED** [review]
good work but Make it sound more technical, it's too lame..

**Comment by MohammedHamzaMalik** [comment]
> good work but Make it sound more technical, it's too lame..

ok

**Comment by itisaby** [comment]
Good nicely done @MohammedHamzaMalik .

**Review by itisaby — APPROVED** [review]

**Review by ahana-mukherjee — APPROVED** [review]
Looks great.

**Comment by MohammedHamzaMalik** [comment]
> Good nicely done @MohammedHamzaMalik .

Thanks

**Comment by itisdb** [comment]
nicely done but i want a bit focus on the star also @MohammedHamzaMalik

**Comment by itisdb** [comment]
well please commit it. merging the code

**Review by itisdb — APPROVED** [review]

**Pull request merged**
